//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eResume
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleDBContainer : DbContext
    {
        public SampleDBContainer()
            : base("name=SampleDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Degree> DegreeSet { get; set; }
        public virtual DbSet<Education> EducationSet { get; set; }
        public virtual DbSet<Author> AuthorSet { get; set; }
        public virtual DbSet<Article> ArticleSet { get; set; }
        public virtual DbSet<Tag> TagSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
        public virtual DbSet<Certificate> CertificateSet { get; set; }
        public virtual DbSet<Skill> SkillSet { get; set; }
        public virtual DbSet<Job> JobSet { get; set; }
        public virtual DbSet<Employer> EmployerSet { get; set; }
        public virtual DbSet<Honor> HonorSet { get; set; }
        public virtual DbSet<Experience> ExperienceSet { get; set; }
        public virtual DbSet<Interest> InterestSet { get; set; }
        public virtual DbSet<Expertise> ExpertiseSet { get; set; }
        public virtual DbSet<SkillLevel> SkillLevelSet { get; set; }
    }
}
